term.clear()
term.setCursorPos(1, 1)
print("Installing...")
shell.run("wget", "https://raw.githubusercontent.com/EphraimBane/CC-ImpendingOS/master/startup.lua", "startup.lua")
shell.run("wget", "https://raw.githubusercontent.com/EphraimBane/CC-ImpendingOS/master/menu.lua", "menu.lua")
shell.run("wget", "https://raw.githubusercontent.com/EphraimBane/CC-ImpendingOS/master/ios/mainmenu.lua", "ios/mainmenu.lua")
shell.run("wget", "https://raw.githubusercontent.com/EphraimBane/CC-ImpendingOS/master/ios/.command.lua", "ios/.command.lua")
shell.run("wget", "https://raw.githubusercontent.com/EphraimBane/CC-ImpendingOS/master/ios/.programs.lua", "ios/.programs.lua")
shell.run("wget", "https://raw.githubusercontent.com/EphraimBane/CC-ImpendingOS/master/ios/programs/mines.lua", "ios/programs/mines.lua")
shell.run("wget", "https://raw.githubusercontent.com/EphraimBane/CC-ImpendingOS/master/ios/programs/othello.lua", "ios/programs/othello.lua")
print("Done!")
os.reboot()
